name: NoReload
main: com.infiniteone.NoReload
version: 2
author: InfiniteOne
description: Cancels the Bukkit /Reload command
commands:
  noreload:
    description: List commands
    usage: /noreload
  noreload help:
    description: List commands
    usage: /noreload help
permissions:
  noreload.nonbypass.*:
    description: Allows use of all non-bypass commands
    default: op
    children:
      noreload.help: true
  noreload.bypass*:
    description: Allows use of all commands
    default: op
    children:
      noreload.help: true
      noreload.reload.bypass: true
      noreload.bypass: true
  noreload.help:
    description: Shows the help dialogue
    default: op
  noreload.bypass:
    description: Bypasses the cancel of /reload
    default: op
  noreload.reload.bypass:
    description: Bypasses the cancel of /reload
    default: op